package cz.kuasta.networkClasses;

public class ServerRatesResponse {
	public double
		STRENGTH_RATIO, INTELECT_RATIO, AGILITY_RATIO, STAMINA_RATIO, LUCK_RATIO,
		ATK_POWER_DIVIDE_RATIO, DODGE_DIVIDE_RATIO, HIT_CHANCE_DIVIDE_RATIO_STRENGTH, HIT_CHANCE_DIVIDE_RATIO_AGILITY;
	
	public ServerRatesResponse(
			double STRENGTH_RATIO, double INTELECT_RATIO, double AGILITY_RATIO, double STAMINA_RATIO, double LUCK_RATIO,
			double ATK_POWER_DIVIDE_RATIO, double DODGE_DIVIDE_RATIO, double HIT_CHANCE_DIVIDE_RATIO_STRENGTH, double HIT_CHANCE_DIVIDE_RATIO_AGILITY
		){
		
		this.STRENGTH_RATIO = STRENGTH_RATIO;
		this.INTELECT_RATIO = INTELECT_RATIO;
		this.AGILITY_RATIO = AGILITY_RATIO;
		this.STAMINA_RATIO = STAMINA_RATIO;
		this.LUCK_RATIO = LUCK_RATIO;
		
		this.ATK_POWER_DIVIDE_RATIO = ATK_POWER_DIVIDE_RATIO;
		this.DODGE_DIVIDE_RATIO = DODGE_DIVIDE_RATIO;
		this.HIT_CHANCE_DIVIDE_RATIO_STRENGTH = HIT_CHANCE_DIVIDE_RATIO_STRENGTH;
		this.HIT_CHANCE_DIVIDE_RATIO_AGILITY = HIT_CHANCE_DIVIDE_RATIO_AGILITY;
	}
}